Create Database Ecommerce;
Use Ecommerce;
CREATE TABLE ecommerce_data (
  InvoiceNo VARCHAR(30),
  StockCode VARCHAR(30),
  Description VARCHAR(200),
  Quantity INT,
  InvoiceDate DATETIME,
  UnitPrice DECIMAL(10,2),
  CustomerID VARCHAR(20),
  Country VARCHAR(40)
);
Show tables; -- show tables in ecommerce data
Set Global local_infile=1; -- Enable local file import
-- Import the file data --
Load data local infile "C:\Users\Dell\Downloads\Ecom.csv"
Into Table ecommerce_data
Fields terminated by ','
Optionally enclosed  by '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country);
select * from ecommerce_data
limit 10;
# calculate the total revenue generated by unitprice and quantity -----
select sum(UnitPrice * Quantity) as TotalRevenue
from ecommerce_data;
 -- Min and Max revenue by county
 select  Country, abs(Min(UnitPrice * Quantity)) as TotalRevenue  from ecommerce_data 
 group by Country
 order by Country desc;
 
 select  Country, abs(Max(UnitPrice * Quantity)) as TotalRevenue  from ecommerce_data 
 group by Country
 order by Country asc;

select * from ecommerce_data limit 10;
-- total order per day
select date(InvoiceDate_clean) As OrderDate ,
count(distinct InvoiceNo) from ecommerce_data
group by OrderDate;

-- Average order --
-- average order = total revenue/ total number of order
select sum(UnitPrice * Quantity) /count(Distinct InvoiceNo) as Average_Order
from ecommerce_data;

SELECT 
    EXTRACT(YEAR FROM InvoiceDate_clean) AS Year,
    EXTRACT(MONTH FROM InvoiceDate_clean) AS Month,

    SUM(Quantity * UnitPrice) AS Total_Revenue,      -- SUM
    COUNT(DISTINCT InvoiceNo) AS Total_Orders,       -- COUNT
    AVG(Quantity * UnitPrice) AS Avg_Order_Value,    -- AVG
    MIN(Quantity * UnitPrice) AS Min_Order_Value,    -- MIN
    MAX(Quantity * UnitPrice) AS Max_Order_Value     -- MAX

FROM ecommerce_data
GROUP BY Year, Month
ORDER BY Year, Month;

